export const experience = [
  {
    id: 'senior-enterprise-solutions-engineer-i',
    title: 'Senior Enterprise Solutions Engineer I',
    date: '2026-09-08',
    company: 'Stellix',
    location: 'Foxborough, MA',
    workMode: 'Remote',
    lead: 'Sep 2026 - Present',
    // No bullets, deliberately. The start date is 2026-09-08 and this was written on
    // 2026-09-04, so no work has been done here yet. The four bullets that used to sit
    // here were lifted from the LinkedIn posting: Syncade installs, VBS/C#/XSLT, SSRS
    // and Crystal Reports, cGMP. That is the employer's description of the role, not a
    // record of anything the owner did, and presenting it as experience is a false
    // claim. Fill this in from real work once there is real work.
  },
  {
    id: 'senior-mes-devops-engineer',
    title: 'Senior MES DevOps Engineer',
    date: '2025-12-01',
    company: 'StarPlus Energy',
    location: 'Kokomo, IN',
    workMode: 'On-site',
    lead: 'Dec 2025 - Sep 2026',
    bullets: [
      'Deploy and test MES releases across Mixing, Electrode, Stack, and Assembly on a live production line',
      'Own month-end ERP settlement and scheduled Oracle maintenance, including data purges, production corrections, and KPI reporting queries',
      'Third-line Systems Operations escalation after Operations Specialists and Process Innovators: controlled data corrections and MES source analysis to determine application intent',
      'Triage shop-floor incidents: trace Linux logs, analyze MES source and git history, document repro steps, and drive fixes with remote developers, DBAs, and IT Infrastructure',
      'Run Jenkins-based MES deployments; maintain disaster recovery runbooks and factory revival procedures',
      'Analyze MES application code (.NET 4.8 WinForms), report defects and fix suggestions to HQ developers; write Python and PowerShell scripts for data and operational automation',
      'Guide local engineering team on git-flow and code management standards across GitHub, GitLab, and Gitea',
    ],
  },
  {
    id: 'mes-software-engineer',
    title: 'MES Software Engineer',
    date: '2024-11-01',
    company: 'StarPlus Energy',
    location: 'Kokomo, IN',
    workMode: 'On-site',
    lead: 'Nov 2024 - Nov 2025',
    bullets: [
      'Supported Stack and Assembly MES on the floor: equipment integration failures, lot tracking, and production hold workflows',
      'Worked with Process Innovation Managers to troubleshoot machinery and equipment issues where MES meets the production line',
      'Debugged UI and backend defects with remote developers; authored SQL data corrections and validated fixes under change control',
      'Guided local software engineering practices and code management for the plant engineering team',
    ],
  },
  {
    id: 'ui-ux-software-engineer',
    title: 'UI / UX Software Engineer',
    date: '2024-01-01',
    company: 'StarPlus Energy',
    location: 'Kokomo, IN',
    workMode: 'On-site',
    lead: 'Jan 2024 - Oct 2024',
    bullets: [
      'Developed MES operator UI components on platform release cycles with distributed engineering teams',
      'Built an internal Vite + React meal-ordering application from scratch; scaled from 350 to 2,600+ users across 4 campuses',
      'Partnered with General Affairs and food vendors as stakeholders while expanding Korean and American menu support',
    ],
  },
  {
    id: 'freelance-web-developer-3fgolf',
    title: 'Freelance Web Developer',
    date: '2023-10-01',
    company: '3FGolf',
    location: 'Remote',
    workMode: 'Remote',
    lead: 'Oct 2023 - Present',
    bullets: [
      'Ship fantasy golf and LLM-powered apps with React, Vite, TailwindCSS, react-query, and Supabase',
      'Integrate third-party sports and news APIs; optimize bundle size, caching, and SEO for production traffic',
    ],
  },
  {
    id: 'software-engineer-colab',
    title: 'Software Engineer',
    date: '2023-09-01',
    company: 'Co.Lab',
    location: 'Seattle, WA',
    workMode: 'Remote',
    lead: 'Sep 2023 - Nov 2023',
    bullets: [
      'Built Matrimoni wedding-planning app in an 8-week sprint',
      'Owned git workflow, app architecture, and the Trello project board',
      'Worked with a co-developer and designer across time zones to hit project deadlines',
    ],
  },
  {
    id: 'full-stack-developer-trainee',
    title: 'Full Stack Developer Trainee',
    date: '2023-04-01',
    company: 'Coding Temple',
    location: 'Chicago, IL',
    workMode: 'Remote',
    lead: 'Apr 2023 - Jun 2023',
    bullets: [
      'Bootcamp focus on Python, Flask, React, TypeScript, JavaScript, HTML/CSS, and SQL',
      'Built full-stack applications with custom REST endpoints and JWT authentication',
      'Oversaw repositories for group projects, including merge and rebase across codebases',
    ],
  },
  {
    id: 'sabbatical',
    title: 'Sabbatical / COVID / Family and Personal Reasons',
    date: '2020-05-01',
    company: 'Health and well-being',
    location: 'Incheon, South Korea',
    lead: '2020 - 2023',
    drawer: [
      'As a first-generation Korean American, my life has been a journey of resilience, adaptation, and personal growth. I moved to the United States in the third grade, a transition that required me to learn a new language and culture. Each subsequent relocation presented its own challenges, but these experiences have shaped me, teaching me the value of friendship and community.',
      'In 2020, my career as a software developer was put on pause due to the pandemic. This unforeseen event became a period of self-reflection and personal development. After graduating from University of Pittsburgh, my parents moved back to Korea. After being unable to visit them for a few years, I decided to reconnect with my family, having conversations I could not have as a kid growing up in the States and deepening my understanding of my roots.',
      "I found joy in unexpected places. I rescued a kitten from the streets. Having never had pets before, I am learning my responsibilities and grateful for a new sense of companionship in my life. I traveled and assisted my aunt and uncle with their restaurant business in Dallas. I also achieved personal milestones such as obtaining my driver's license and being the best man at a wedding. Towards the end of this period, I had the unique opportunity to fly to Korea to interview for a graduate program in cybersecurity at Korea University. Although I did not get in, it was a valuable experience that allowed me to explore a new academic path.",
      "Technology has been a constant companion throughout my life. From using a PC since Windows 95, to building desktop computers for friends and family, to marveling at the vast capabilities of the internet, my fascination with technology has remained steadfast. I am eager to apply the skills I've acquired, the stability I've developed, and the passion I've reignited to contribute to the ever-evolving world of technology.",
    ],
  },
  {
    id: 'application-developer',
    title: 'Application Developer',
    date: '2019-03-01',
    company: 'Highmark Health Solutions',
    location: 'Pittsburgh, PA',
    workMode: 'Hybrid',
    lead: 'Mar 2019 - May 2020',
    bullets: [
      'Lead developer on a clinical web portal for patient data search; mentored a developer on Vue with a Java backend',
      'Collaborated within a Scrum team, managed story points for sprints, and maintained GitLab git-flow',
      'Configured Babel for IE7 compatibility and championed Vue adoption within the company',
      "Maintained and developed Highmark's Utilization Management tooling on the PegaSystems platform",
    ],
  },
  {
    id: 'web-developer',
    title: 'Web Developer',
    date: '2017-09-01',
    company: 'Checkmate Digital',
    location: 'New Haven, CT',
    workMode: 'Remote',
    lead: 'Sep 2017 - Jan 2019',
    bullets: [
      'Delivered end-to-end web applications for startup clients in an agency environment',
      'Led Angular-to-React migration with the CTO; established component patterns and build tooling for the new stack',
      'Worked across the product lifecycle from concept through deployment under client deadlines',
    ],
  },
]
