export const experience = [
  {
    id: 'manufacturing-execution-systems-software-engineer',
    title: 'Manufacturing Execution Systems Software Engineer',
    date: '2024-11-01',
    company: 'StarPlus Energy',
    location: 'Kokomo, IN',
    workMode: 'On-site',
    bullets: [
      "Dedicated Software Engineer for the factory's Stack and Assembly shop division",
      'Work closely with Process Innovation Managers to problem solve and respond intuitively to troubleshoot machinery and equipment on the factory floor',
      'Facilitate company with technical communication by effectively translating and interpreting written and spoken English and Korean in a dual cultural joint venture environment',
      'Lead and guide software engineering team with knowledge and information, establishing efficient team dynamic as well as environment for proper code management',
    ],
  },
  {
    id: 'ui-ux-software-engineer',
    title: 'UI / UX Software Engineer',
    date: '2024-01-01',
    company: 'StarPlus Energy',
    location: 'Kokomo, IN',
    workMode: 'On-site',
    bullets: [
      'Develop intuitive user interface and assess proper data management for the Manufacturing Execution System affiliated with Samsung SDI and Samsung SDS',
      'Created a web application for an initial user base of 350 employees to select provided Korean food options for lunch and dinner at the company. Continuing to scale up the project based on the growth of the company. Now also handling American (Continental) cuisine alongside Korean cuisine for the menu',
      'Currently serving 2200+ individual user accounts for 4 different company campuses and providing efficient solutions for General Affairs and various food vendors for the company',
    ],
  },
  {
    id: 'software-engineer-colab',
    title: 'Software Engineer',
    date: '2023-11-01',
    company: 'Co.Lab',
    location: 'Seattle, WA',
    workMode: 'Remote',
    bullets: [
      "Completed an intensive 8-week program, where I played a pivotal role in developing the 'Matrimoni' app, a search engine tool designed to simplify wedding planning.",
      'Developed effective workarounds for app functionality, showcasing adaptability and innovation in software development.',
      'Managed git flow, app architecture, and the Trello project board, demonstrating strong organizational skills and a clear understanding of project lifecycle.',
      'Worked closely with a co-developer and a designer, adapting to role changes and communication challenges. This experience highlighted the importance of teamwork and clear requirements for project success.',
      'Restructured daily schedule to align with team members in different time zones, displaying flexibility and commitment to project deadlines.',
    ],
  },
  {
    id: 'full-stack-developer-trainee',
    title: 'Full Stack Developer Trainee',
    date: '2023-07-01',
    company: 'Coding Temple',
    location: 'Chicago, IL',
    workMode: 'Remote',
    bullets: [
      'Graduated from a rigorous bootcamp with a focus on Python, Flask, React, Typescript, Javascript, HTML/CSS, and SQL',
      'Enhanced programming proficiency by developing diverse personal projects, honing syntax knowledge, and adopting modern coding standards',
      'Gained experience integrating third-party APIs and libraries, building full-stack applications with custom endpoints and JWT',
      'Oversaw repositories for group projects, directing merge and rebase operations of different codebases',
    ],
  },
  {
    id: 'sabbatical',
    title: 'Sabbatical / COVID / Family and Personal Reasons',
    date: '2023-03-01',
    company: 'Health and well-being',
    location: 'Incheon, South Korea',
    drawer: [
      'As a first-generation Korean American, my life has been a journey of resilience, adaptation, and personal growth. I moved to the United States in the third grade, a transition that required me to learn a new language and culture. Each subsequent relocation presented its own challenges, but these experiences have shaped me, teaching me the value of friendship and community.',
      'In 2020, my career as a software developer was put on pause due to the pandemic. This unforeseen event became a period of self-reflection and personal development. After graduating from University of Pittsburgh, my parents moved back to Korea. After being unable to visit them for a few years, I decided to reconnect with my family, having conversations I could not have as a kid growing up in the States and deepening my understanding of my roots.',
      'I found joy in unexpected places. I rescued a kitten from the streets. Having never had pets before, I am learning my responsibilities and grateful for a new sense of companionship in my life. I traveled and assisted my aunt and uncle with their restaurant business in Dallas. I also achieved personal milestones such as obtaining my driver\'s license and being the best man at a wedding. Towards the end of this period, I had the unique opportunity to fly to Korea to interview for a graduate program in cybersecurity at Korea University. Although I did not get in, it was a valuable experience that allowed me to explore a new academic path.',
      'Technology has been a constant companion throughout my life. From using a PC since Windows 95, to building desktop computers for friends and family, to marveling at the vast capabilities of the internet, my fascination with technology has remained steadfast. I am eager to apply the skills I\'ve acquired, the stability I\'ve developed, and the passion I\'ve reignited to contribute to the ever-evolving world of technology. I am ready to embark on this next chapter of my journey and look forward to the opportunities it will bring.',
    ],
  },
  {
    id: 'application-developer',
    title: 'Application Developer',
    date: '2020-05-01',
    company: 'Highmark Health Solutions',
    location: 'Pittsburgh, PA',
    workMode: 'Hybrid',
    bullets: [
      'Served as lead developer for a web portal project enabling healthcare professionals to search patient data based on UMI',
      'Collaborated within a full scrum team, managed story points for sprints, and mentored a fellow developer in Javascript/HTML/CSS to utilize Vue with a Java backend',
      'Maintained git-flow with GitLab, configured the Babel Transpiler for IE7 compatibility and championed the adoption of Vue as a framework within the company',
      "Leveraged the PegaSystems Platform to maintain and develop Highmark's Utilization Management tool for healthcare professionals in Pittsburgh",
    ],
  },
  {
    id: 'web-developer',
    title: 'Web Developer',
    date: '2019-01-01',
    company: 'Checkmate Digital',
    location: 'New Haven, CT',
    workMode: 'Remote',
    lead:
      'Developed operational web apps for other tech startups, translating high-fidelity designs into fully functional digital solutions',
    bullets: [
      "Engaged in end-to-end project development, collaborating with the UX/UI team and providing comprehensive web solutions for tech startup clients under the agency's purview",
      "Pioneered a tech stack transition from Angular to React in close partnership with the CTO, enhancing the agency's technological capabilities",
      'Expanded technical knowledge by learning various JavaScript frameworks and libraries, adhering to industry-defined coding standards, and implementing effective git-flow practices',
      'Cultivated a deep understanding of the product life cycle, contributing to all stages from conceptualization to deployment',
    ],
  },
]
